[package]
name = "mathcat4j"
version = "0.1.0"
edition = "2021"
authors = ["Michael Whapples"]

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.19.0"
mathcat = { path = "../MathCAT" }

[build-dependencies]
zip = { version = "2.1", default-features = false, features = ["bzip2"] }
